# Generated by Django 4.0.6 on 2022-09-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_coupon_minimun_amount'),
        ('carts', '0011_remove_cartitem_coupon_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.coupon'),
        ),
    ]
