# Generated by Django 4.0.6 on 2022-09-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_cartitem_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
