# Generated by Django 4.0.6 on 2022-09-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_remove_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
