# Generated by Django 4.0.6 on 2022-08-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_mobile_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='fname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='lname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='phone',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='pincode',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='state',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
