# Generated by Django 4.0.6 on 2022-09-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraddressbook_city_useraddressbook_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
