# Generated by Django 4.0.6 on 2022-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
