# Generated by Django 4.0.6 on 2022-08-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='photos/products')),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('orignal_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0-default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default, 1=Trending')),
                ('tag', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
