# Generated by Django 4.0.6 on 2022-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orignal_price',
            field=models.FloatField(null=True),
        ),
    ]
