# Generated by Django 4.0.6 on 2022-08-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
