# Generated by Django 4.0.6 on 2022-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_1',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
