# Generated by Django 4.0.6 on 2022-09-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_product_product_image_1_product_product_image_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=100)),
            ],
        ),
    ]
