# Generated by Django 4.0.6 on 2022-09-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimun_amount',
            field=models.IntegerField(default=500),
        ),
    ]
