# Generated by Django 4.0.6 on 2022-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0019_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(null=True),
        ),
    ]
