# Generated by Django 4.0.6 on 2022-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount_amnt',
            field=models.FloatField(null=True),
        ),
    ]
