# Generated by Django 4.0.6 on 2022-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0021_category_discount_amnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='is_expired',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='is_expired',
            field=models.BooleanField(default=True),
        ),
    ]
