# Generated by Django 4.0.6 on 2022-09-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_alter_categoryoffer_is_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
