# Generated by Django 4.0.6 on 2022-09-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0023_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_amnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
