# Generated by Django 4.0.6 on 2022-09-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0025_filter_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter_Price',
        ),
    ]
