# Generated by Django 4.0.6 on 2022-09-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0030_pricefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefilter',
            name='price',
            field=models.CharField(blank=True, choices=[('1000 TO 10000', '1000 TO 10000'), ('10000 TO 20000', '10000 TO 20000'), ('20000 TO 30000', '20000 TO 30000'), ('30000 TO 40000', '30000 TO 40000'), ('40000 TO 50000', '40000 TO 50000')], default='default', max_length=60, null=True),
        ),
    ]
