# Generated by Django 4.0.6 on 2022-08-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_delete_cart'),
        ('orders', '0002_remove_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.product'),
        ),
    ]
